spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://wetech.tech:3306/wetech_admin
    url: jdbc:mysql://localhost:3306/wetech_admin?serverTimezone=GMT
    username: root
    password: 1382822201
    hikari:
        max-lifetime: 1000000
