spring:
  application:
    name: wetech-admin
  profiles:
    active: @spring.application.proflies@ # 设置激活的环境
  main:
      lazy-initialization: true
mybatis: # mybatis 配置
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
    global-config:
        db-config:
            id-type: assign_uuid
            logic-delete-field: isDelete  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
            logic-delete-value: "1" # 逻辑已删除值(默认为 1)
            logic-not-delete-value: "0" # 逻辑未删除值(默认为 0)
            where-strategy: not_empty


password: #shiro
  algorithmName: md5
  hashIterations: 2
